cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete

os: linux
dist: trusty
sudo: required

language: scala
scala: 2.12.7
jdk: openjdk8

sbt_args: -no-colors -J-Xss2m -J-Xms1g -J-Xmx3g -J-XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF8

script:
- sbt ++$TRAVIS_SCALA_VERSION test

branches:
  only:
  - master
  - develop
  - /^.*head$/
